name: Deploy "My Little Board"

on:
  workflow_call:
      inputs:
        environment:
          required: true
          type: string

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: blazor-server-app
          path: ./blazor-server-app

      - name: Download Database artifact
        uses: actions/download-artifact@v4
        with:
          name: efbundle
          path: ./efbundle

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Run Database migrations
        env:
          ConnectionStrings__Default: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: |
          chmod +x ./efbundle/efbundle
          ./efbundle/efbundle

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-mlb-dev'
          slot-name: 'Production'
          package: ./blazor-server-app
