# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy "My Little Board", Blazor Server App

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Directory.**.props"
      - "global.json"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test .NET projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release --property:PublishDir=${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: blazor-server-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Restore Tools
        run: dotnet tool restore

      - name: Bundle EF bundle
        run: |
          dotnet ef migrations bundle \
          --startup-project src/Server \
          --project src/Infrastructure \
          --configuration Release \
          --self-contained \
          --no-build \
          --force

      - name: Publish database bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: efbundle
          path: ./efbundle

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: blazor-server-app
          path: ./blazor-server-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Run Database migrations
        env:
          ConnectionStrings__Default: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: |
          chmod +x ./efbundle/efbundle
          ./efbundle/efbundle

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-mlb-dev'
          slot-name: 'Production'
          package: ./blazor-server-app
