name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    strategy:
      matrix:
        target: [Production]
    name: Terraform - ${{ matrix.target }}
    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.target }}
      directory: ./iac/environments/production
    secrets: inherit
    permissions:
      id-token: write # This is required for requesting the JWT
      pull-requests: write

  build:
    name: Test .NET projects and IAC
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      pull-requests: write
    strategy:
      matrix:
        environment: [Production]
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --configuration Release --verbosity normal
